FROM node:12.14.1.-alpine

# Create app directory
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3030

# Commands at runtime
CMD [ "npm", "run", "start" ]
